services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4 # You can change the version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory allocation as needed
      - xpack.security.enabled=false # Disable security for local development simplicity
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4 # Use the same version as Elasticsearch
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Points to the Elasticsearch container
    depends_on:
      - elasticsearch
    networks:
      - elastic
      
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - elastic
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
              # Remove the GPU related settings if you don't have a GPU

volumes:
  esdata:
    driver: local
  ollama_data:
    driver: local

networks:
  elastic:
    driver: bridge
